### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by lyt19931029** [stephen-v/tensorflow_alexnet_classify#2]
您好,我修改了main_alexnet.py,用到自己的数据集训练,结果报错

lyt@lyt-Default-string:~/tensorflow_alexnet_classify-master$ python3 main_alexnet.py 
Traceback (most recent call last):
  File "main_alexnet.py", line 12, in <module>
    from datagenerator import ImageDataGenerator
  File "/home/lyt/tensorflow_alexnet_classify-master/datagenerator.py", line 7, in <module>
    from tensorflow.data import Dataset
ImportError: No module named 'tensorflow.data'

**Comment by A1exy** [comment]
请问解决了这个问题没，我是Tensorflow 1.8的环境。

**Comment by A1exy** [comment]
https://github.com/tensorflow/tensorflow/issues/14875，最后一楼的回复，改写下问题解决。

**Comment by lyt19931029** [comment]
谢谢，我这个问题已经解决了

在 2018-12-26 13:31:11，"A1exy" <notifications@github.com> 写道：


请问解决了这个问题没，我是Tensorflow 1.8的环境。

**Comment by DavidLeeDVD** [comment]
> 您好,我修改了main_alexnet.py,用到自己的数据集训练,结果报错
> 
> lyt@lyt-Default-string:~/tensorflow_alexnet_classify-master$ python3 main_alexnet.py
> Traceback (most recent call last):
> File "main_alexnet.py", line 12, in 
> from datagenerator import ImageDataGenerator
> File "/home/lyt/tensorflow_alexnet_classify-master/datagenerator.py", line 7, in 
> from tensorflow.data import Dataset
> ImportError: No module named 'tensorflow.data'

from tensorflow.contrib.data import Iterator

**Comment by liujianghao1023** [comment]
同样问下 这个 data  import 怎么搞的
