### ISSUE TITLE
关于模型批量验证的问题

### ISSUE THREAD

**Issue by YasinChou** [stephen-v/tensorflow_alexnet_classify#5]
我在对多个图片批量验证时，第一个没有出错，遍历第二个以后就报错，不知道为什么

>   2019-09-26 10:05:21.685416: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at save_restore_v2_ops.cc:184 : Not found: Key conv1_1/biases not found in checkpoint
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1356, in _do_call
    return fn(*args)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1341, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1429, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.NotFoundError: Key conv1_1/biases not found in checkpoint
	 [[{{node save_1/RestoreV2}}]]

**Comment by YasinChou** [comment]
问题已经找到，参见：https://blog.csdn.net/zhou4411781/article/details/101459735

**Comment by YasinChou** [comment]
去掉with as 结构图后，计算图感觉有点乱，请问博主上述链接正确吗？with tf.name_scope(‘xxx’) as scope去掉后会影响吗
